version: '3'
services:
  steady-web:
    build:
      context: ./
      dockerfile: steady-marketplace/docker/Dockerfile
    ports:
      - "80:4200"
    container_name: steady-web
    volumes:
       - ./steady-marketplace:/usr/src/app/steadyWeb
       